version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    environment:
      - MONGO_INITDB_DATABASE=db
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=CHANGEME
      - TZ="Europe/Madrid"
    volumes:
      - db:/data/db
  web:
    image: abemposta/passiveanalysis
    container_name: passive_analysis
    environment:
        DOMAIN: "example.org"
        MONGO_DB: "db"
        MONGO_USER: "user"
        MONGO_PASSWORD: "CHANGEME"
        MONGO_HOST: "mongo"
        MONGO_PORT: "27017"
        MONGO_AUTH_SOURCE: "admin"
        MONGO_COLLECTION: "packets"
        TZ: "Europe/Madrid"

    ports:
      - "8000:8000"
    depends_on:
      - mongo
volumes:
  db:

