version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo_tfg
    environment:
      - MONGO_INITDB_DATABASE=tfg
      - MONGO_INITDB_ROOT_USERNAME=tfg_mongo
      - MONGO_INITDB_ROOT_PASSWORD=Secret1
      - TZ=Europe/Madrid
    ports:
      - 27017:27017
    volumes:
      - tfg_db:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: tfg_mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: Secret1
  web:
    build: .
    container_name: web_tfg
    environment:
        ENVIRONMENT: "development"
        MONGO_DB: "tfg"
        MONGO_USER: "tfg_mongo"
        MONGO_PASSWORD: "Secret1"
        MONGO_HOST: "mongo"
        MONGO_PORT: "27017"
        MONGO_AUTH_SOURCE: "admin"
        MONGO_COLLECTION: "packets"
        TZ: "Europe/Madrid"

    volumes:
      - .:/code
    ports:
      - "8000:8080"
    depends_on:
      - mongo
volumes:
  tfg_db:

